volumes:
  data:
    name: postgresql_data
  initdb:
    name: postgresql_initdb
  preinitdb:
    name: postgresql_preinitdb

networks:
  service:
    name: postgresql_service

services:
  postgresql:
    image: bitnami/postgresql:17.3.0
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - service
    volumes:
      - data:/bitnami/postgresql
      - initdb:/docker-entrypoint-initdb.d
      - preinitdb:/docker-entrypoint-preinitdb.d
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ../stack.env
