volumes:
  data:
    name: postgresql_data
  initdb:
    name: postgresql_initdb
  preinitdb:
    name: postgresql_preinitdb

networks:
  internal:
    name: postgresql_internal
    internal: true
  external:
    name: postgresql_external

services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - internal
      - external
    volumes:
      - data:/bitnami/postgresql
      - initdb:/docker-entrypoint-initdb.d
      - preinitdb:/docker-entrypoint-preinitdb.d
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ../stack.env
