volumes:
  data:
    name: postgresql_data
  initdb:
    name: postgresql_initdb
  preinitdb:
    name: postgresql_preinitdb

services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - data:/bitnami/postgresql
      - initdb:/docker-entrypoint-initdb.d
      - preinitdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
