name: vaultwarden-backup

volumes:
  vw-data:
    name: vaultwarden_data
    external: true
  rclone:
    name: vaultwarden-backup_rclone
    external: true

services:
  vw-backup:
    image: ttionya/vaultwarden-backup:1.24.0
    container_name: vaultwarden-backup
    restart: unless-stopped
    environment:
      RCLONE_REMOTE_NAME: "BitwardenBackup"
      RCLONE_REMOTE_DIR: "/BitwardenBackup/"
      RCLONE_GLOBAL_FLAG: ""
      CRON: "0 0 * * *"
      ZIP_ENABLE: "TRUE"
      ZIP_PASSWORD: ${ZIP_PASSWORD}
      ZIP_TYPE: "zip"
      BACKUP_FILE_SUFFIX: "%Y%m%d"
      BACKUP_KEEP_DAYS: 7
      TIMEZONE: "Asia/Tokyo"
    volumes:
      - vw-data:/bitwarden/data/
      - rclone:/config/
    env_file:
      - ../stack.env
