volumes:
  data:
    name: misskey_redis_data

services:
  redis:
    image: bitnami/redis
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - ${MY_PORT_NUMBER_REDIS}:6379
    volumes:
      - data:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - ../../stack.env
