name: redis
services:
  redis:
    image: redis:8.0.2@sha256:dac8ab0340cef636bf80c4d771e338733c694885567aaabd15fe1368d6bf7c13
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
