name: redis
services:
  redis:
    image: redis:8.0.3@sha256:1d6915eb047b8e73ab65e67950a29ee167248a08b0c046b29053aff33c5aeb5c
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
