name: redis
services:
  redis:
    image: redis:8.0.3@sha256:d439e4cc4d58ddc21012981d27da1e81a04159cc01bf5a039136d33a0d21c4c9
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
