name: redis
services:
  redis:
    image: redis:8.0.2@sha256:f63ce21b73ded27fbf9cd355c05877428b9718364026d810dfa8cce0f95428eb
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
