name: redis
services:
  redis:
    image: redis:8.0.2@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
