name: redis
services:
  redis:
    image: redis:8.0.3@sha256:a1e0a3b3a6cedd74d8ba44805b2497b93851a296f08a44962fedc03f1c490b47
    container_name: misskey_redis
    restart: unless-stopped
    ports:
      - 56379:6379
    volumes:
      - data:/data

volumes:
  data:
    name: misskey_redis_data
