services:
  postgres_nextcloud:
    image: postgres:16.10@sha256:3c2aa0f6e0a0f71adf7c362c7278578148ae697e37b0224c0e1bbadb9d2a2058
    container_name: postgres_nextcloud
    restart: unless-stopped
    ports:
      - 65434:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_nextcloud_data
