services:
  postgres_nextcloud:
    image: postgres:16.9@sha256:ddfe3e8713e3ee5b8f286082cb12512488dfbf3f5a1ecb0b74a42e6055af0a5f
    container_name: postgres_nextcloud
    restart: unless-stopped
    ports:
      - 65434:5432
    volumes:
      - data:/var/lib/postgresql/data
      - /srv/postgres/nextcloud/log:/log
    command: >
      -c 'logging_collector=on'
      -c 'log_directory=/log'
      -c 'log_filename=postgresql.log'
      -c 'log_timezone=Asia/Tokyo'
      -c 'log_truncate_on_rotation=on'
      -c 'log_statement=all'
      -c 'log_connections=on'
      -c 'log_disconnections=on'
      -c 'log_lock_waits=on'
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_nextcloud_data
