services:
  postgres_nextcloud:
    image: postgres:16.9@sha256:1698211a8af0dcb0d86356da9f0ffe9ae524143a6b8bf148ad7c4ad3ef8c95a4
    container_name: postgres_nextcloud
    restart: unless-stopped
    ports:
      - 65434:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_nextcloud_data
