services:
  postgres_nextcloud:
    image: postgres:16.9@sha256:a1fa9f5b1d96f285420374f96e2b9952e4221d71c2c3bb22c1f52dd61bcf9e06
    container_name: postgres_nextcloud
    restart: unless-stopped
    ports:
      - 65434:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_nextcloud_data
