services:
  postgres_nextcloud:
    image: postgres:16.9@sha256:fea8055d20c65344b914558976d5e4ffb77b1ed99d93ebe9a1a0a6c9e43e37ce
    container_name: postgres_nextcloud
    restart: unless-stopped
    ports:
      - 65434:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_nextcloud_data
