name: traefik
services:
  traefik:
    image: traefik:v3.3.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.http-01-solver.acme.tlschallenge=true"
      - "--certificatesresolvers.http-01-solver.acme.storage=/letsencrypt/acme.json"

volumes:
  letsencrypt:
    name: traefik_letsencrypt
