services:
  postgres_misskey:
    image: groonga/pgroonga:4.0.1-debian-17@sha256:ca3e4c3f11d7a41a8395141a1c8e74236b48b10ef1a4548f3aaacee11bf593d9
    container_name: postgres_misskey
    restart: unless-stopped
    ports:
      - 65432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - /srv/postgres/log:/log
    command: >
      -c 'logging_collector=on'
      -c 'log_directory=/log'
      -c 'log_filename=misskey-%Y-%m-%d_%H%M%S.log'
      -c 'log_file_mode=0644'
      -c 'log_timezone=Asia/Tokyo'
      -c 'log_truncate_on_rotation=on'
    environment:
      POSTGRES_USER: misskey
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: misskey
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_misskey_data
