name: redis
services:
  redis:
    image: redis:8.0.1@sha256:c49bdcc516aa4b2d66d8a46526afd7d38f2e53d069c5a2c1cb0efe76ebffa737
    container_name: redis_nextcloud
    restart: unless-stopped
    ports:
      - 56380:6379
    volumes:
      - data:/data

volumes:
  data:
    name: redis_nextcloud_data
