name: redis
services:
  redis:
    image: redis:8.2.1@sha256:cc2dfb8f5151da2684b4a09bd04b567f92d07591d91980eb3eca21df07e12760
    container_name: redis_nextcloud
    restart: unless-stopped
    ports:
      - 56380:6379
    volumes:
      - data:/data

volumes:
  data:
    name: redis_nextcloud_data
