name: redis
services:
  redis:
    image: redis:8.0.1@sha256:1b7c17f650602d97a10724d796f45f0b5250d47ee5ba02f28de89f8a1531f3ce
    container_name: redis_nextcloud
    restart: unless-stopped
    ports:
      - 56380:6379
    volumes:
      - data:/data

volumes:
  data:
    name: redis_nextcloud_data
