name: redis
services:
  redis:
    image: redis:8.0.2@sha256:ad628d213d00627d78094bd0da550d7abb59649e2c8fda74eed4c80794a577dc
    container_name: redis_nextcloud
    restart: unless-stopped
    ports:
      - 56380:6379
    volumes:
      - data:/data

volumes:
  data:
    name: redis_nextcloud_data
