services:
  postgres_vaultwarden:
    image: postgres:17.5@sha256:fc50da4d6d6bb989a167cf8c48317a2a9e9387bd8b9067a2750daa9eca73a4f6
    container_name: postgres_vaultwarden
    restart: unless-stopped
    ports:
      - 65433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vaultwarden
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_vaultwarden_data
