services:
  postgres_vaultwarden:
    image: postgres:17.5@sha256:aadf2c0696f5ef357aa7a68da995137f0cf17bad0bf6e1f17de06ae5c769b302
    container_name: postgres_vaultwarden
    restart: unless-stopped
    ports:
      - 65433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vaultwarden
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_vaultwarden_data
