services:
  postgres_vaultwarden:
    image: postgres:17.5@sha256:4d89c904835259bc58876520e56267ca07a4ebd6a027f7814bbbf91b50d685be
    container_name: postgres_vaultwarden
    restart: unless-stopped
    ports:
      - 65433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vaultwarden
    env_file:
      - ../../stack.env

volumes:
  data:
    name: postgres_vaultwarden_data
