name: portainer
services:
  portainer-ce:
    image: portainer/portainer-ce:2.31.2@sha256:eb7864f3cd4e31e6fe98db53fa5680bfbc627442a87b65770171ad8a822dec0b
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: portainer_data
