name: portainer
services:
  portainer-ce:
    image: portainer/portainer-ce:2.28.1
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - cf-tunnel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: portainer_data

networks:
  cf-tunnel:
    name: cf-tunnel
    external: true
