name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.4.2
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    networks:
      - cf-tunnel
    env_file:
      - ../stack.env

networks:
  cf-tunnel:
    name: cf-tunnel
    external: true
