name: minio
services:
  image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  container_name: minio
  restart: unless-stopped
  command: server /data --console-address ":9001"
  ports:
    - "9000:9000"
    - "9001:9001"
  environment:
    MINIO_ROOT_USER: ${ROOT_USER}
    MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD}
  volumes:
    - data:/data

volumes:
  data:
    name: minio_data
