name: portainer-agent
services:
  portainer-agent:
    image: portainer/agent:2.21.5
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
